apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-05-08T14:09:36Z"
  labels:
    run: nginx
  name: nginx
  namespace: default
  resourceVersion: "575"
  selfLink: /api/v1/namespaces/default/pods/nginx
  uid: 8cb2dd56-9135-11ea-8840-0800270e5bf2
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-2xzss
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: minikube
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-2xzss
    secret:
      defaultMode: 420
      secretName: default-token-2xzss
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-05-08T14:09:36Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-05-08T14:09:42Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-05-08T14:09:36Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://03e9ba43097bca0aa729926e639ad26a1c8e5f537624237ad5f9fed040c0bedb
    image: nginx:latest
    imageID: docker-pullable://nginx@sha256:86ae264c3f4acb99b2dee4d0098c40cb8c46dcf9e1148f05d3a51c4df6758c12
    lastState: {}
    name: nginx
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2020-05-08T14:09:42Z"
  hostIP: 192.168.99.100
  phase: Running
  podIP: 172.17.0.5
  qosClass: BestEffort
  startTime: "2020-05-08T14:09:36Z"
